export type RecordSpeciesTone = 'cow' | 'sheep' | 'pig' | 'goat' | 'neutral';

export type RecordEntry = {
  id: string;
  date: string;
  animal: string;
  animalTag: string;
  animalIds?: string[];
  species: string;
  speciesTone: RecordSpeciesTone;
  title: string;
  details: string;
  type: string;
  medicine?: string;
  dose?: string;
  doseUnit?: string;
  route?: string;
  withdrawal?: string;
  imageUris?: string[];
  recordTitle?: string;
  weight?: string;
  weightUnit?: string;
  causeOfDeath?: string;
  disposalMethod?: string;
  healthStatus?: string;
  conditionDiagnosis?: string;
  vetSeen?: 'Yes' | 'No';
  buyer?: string;
  salePrice?: string;
  destination?: string;
  seller?: string;
  purchasePrice?: string;
  sourceFarm?: string;
  motherName?: string;
  birthTagId?: string;
  birthSpecies?: string;
  birthBreed?: string;
  birthSex?: 'female' | 'male';
  birthWeight?: string;
  birthWeightUnit?: string;
  fromFarm?: string;
  fromPaddock?: string;
  toFarm?: string;
  toPaddock?: string;
};
